version: "3.8"
services:
  app:
    build: ./
    container_name: app
    volumes:
      - ./:/app
    working_dir: /app
  mq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
